[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["cd WonderlandBackend && dotnet restore"]

[phases.build]
cmds = ["cd WonderlandBackend && dotnet publish -c Release -o out"]

[start]
cmd = "cd WonderlandBackend && dotnet out/WonderlandBackend.dll"