[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["cd backend/WonderlandBackend && dotnet publish -c Release -o out"]

[start]
cmd = "cd backend/WonderlandBackend && dotnet out/WonderlandBackend.dll"